version: "3.7"

services:
  db:
    image: postgres:12-alpine
    container_name: "galactic-trade-auth-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
    networks:
      - galactic-trade
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: "galactic-trade-auth-rest-api"
    environment:
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DB=$DB_DB
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - SSL_MODE=$SSL_MODE
      - JWT_KEY=$JWT_KEY
      - SEED_IF_EMPTY=$SEED_IF_EMPTY
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - galactic-trade

volumes:
  database_postgres:

networks:
  galactic-trade:
    driver: bridge
